export const REQUEST_LIST = 'REQUEST_LIST';
export const RECEIVE_LIST = 'RECEIVE_LIST';
export const REQUEST_ITEM_LIST = 'REQUEST_ITEM_LIST';
export const RECEIVE_ITEM_LIST = 'RECEIVE_ITEM_LIST';
export const REQUEST_UPDATE = 'REQUEST_UPDATE';
export const RECEIVE_UPDATE = 'RECEIVE_UPDATE';
